### ISSUE TITLE
gulp-react-templates out of date resulting in incompatible dependency versions

### ISSUE THREAD

**Issue by ADagen** [wix/gulp-react-templates#10]
Hello,

a clean installation of "gulp-react-templates" results in a broken install of version 0.2.0.

Cause: Dependency "react-templates" is stated with version "^0.4.1" and pulled with version 0.4.2, which has some breaking changes, causing gulp to fail:

```
TypeError: _.restParam is not a function
    at Object.<anonymous> (<...>/node_modules/gulp-react-templates/node_modules/react-templates/dist/RTCodeError.js:121:29)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (<...>/node_modules/gulp-react-templates/node_modules/react-templates/dist/reactTemplates.js:11:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

```

I worked around by explicitly adding "react-templates": "0.4.1" (with lodash@3) to my project's package.json.

Can you fix this?

Thanks so much!
Best,
Andrei

**Comment by idok** [comment]
fixed
